function plot_ud(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 07-Nov-2013 00:34:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','FontWeight','demi',...
    'FontSize',12);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-10155.4946448063 10155.3187268972]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','Scurve');
set(plot1(2),'LineWidth',1,'Color',[1 1 0],'DisplayName','ScurveTeor');
set(plot1(3),'LineStyle','--','DisplayName','Sd');
set(plot1(4),'LineStyle','--','DisplayName','SdTeor','Color',[0 0 0]);

% Create xlabel
xlabel('\delta\phi, deg','FontWeight','demi','FontSize',12);

% Create ylabel
ylabel('M[ud_{\phi}(\delta\phi)]','FontWeight','normal','FontSize',12);

