function plot_Dphi(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 16-Nov-2013 18:14:12

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','FontSize',12);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'MarkerSize',15,'Marker','.','LineStyle','none',...
    'Color',[1 0 0]);
set(plot1(2),'Color',[0 0 1]);
set(plot1(3),'LineStyle','--','Color',[0 0 0]);

% Create xlabel
xlabel('q_{c/n0}, dBHz','FontSize',12);

% Create ylabel
ylabel('\sigma_{ekv}, deg','FontSize',12);

